pipeline {
    agent { label 'UBUNTU_NODE1' }
    stages {
        stage('vcs') {
            steps {
                git url: 'https://github.com/Madhuri-chinta/terraformworkspace.git',
                    branch: 'main'
            }
        }
        stage('terraform') {
            steps {
                sh """cd jen.terraform
                      terraform init
                      terraform apply -var-file ./values.tfvars -auto-approve
                      terraform destroy -var-file ./values.tfvars -auto-approve"""
            }
        }
    }
}