pipeline {
    agent { label 'UBUNTU_NODE1' }
    stages {
        stage('vcs') {
            steps {
                git url: 'https://github.com/Madhuri-chinta/terraformworkspace.git',
                    branch: 'main'
            }
        }
        stage('terraform') {
            steps {
                sh 'cd jen.terraform'
                sh 'terraform init'
                sh 'terraform apply -var-file ./jen.terraform/values.tfvars -auto-approve'
            }
        }
    }
}